project:
  type: website
  output-dir: docs     # tudo que for gerado vai para /docs (GitHub Pages vai servir daqui)

website:
  title: "Introdução à Programação em R"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - text: Materiais
        menu:
          - href: materiais.qmd
            text: Apostila & Arquivos
  sidebar:
    style: "docked"
    search: true

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: false
